name: toolgrad
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - libcxx=17.0.6
  - libffi=3.4.4
  - libmpdec=4.0.0
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.13.5
  - python_abi=3.13
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anthropic==0.59.0
      - anyio==4.9.0
      - attrs==25.3.0
      - cachetools==5.5.2
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - click==8.2.1
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - filetype==1.2.0
      - frozenlist==1.7.0
      - gin-config==0.5.0
      - google-ai-generativelanguage==0.6.18
      - google-api-core==2.25.1
      - google-auth==2.40.3
      - googleapis-common-protos==1.70.0
      - greenlet==3.2.3
      - groq==0.30.0
      - grpcio==1.74.0
      - grpcio-status==1.74.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - idna==3.10
      - jiter==0.10.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - langchain==0.3.25
      - langchain-anthropic==0.3.17
      - langchain-community==0.3.25
      - langchain-core==0.3.72
      - langchain-deepseek==0.1.4
      - langchain-google-genai==2.1.8
      - langchain-groq==0.3.6
      - langchain-mcp-adapters==0.1.9
      - langchain-openai==0.3.28
      - langchain-text-splitters==0.3.8
      - langchain-together==0.3.0
      - langgraph==0.4.8
      - langgraph-checkpoint==2.1.0
      - langgraph-prebuilt==0.2.2
      - langgraph-sdk==0.1.70
      - langsmith==0.3.45
      - markdown-it-py==3.0.0
      - marshmallow==3.26.1
      - mcp==1.11.0
      - mdurl==0.1.2
      - multidict==6.5.0
      - mypy-extensions==1.1.0
      - numpy==2.3.0
      - openai==1.88.0
      - orjson==3.10.18
      - ormsgpack==1.10.0
      - packaging==24.2
      - pandas==2.3.1
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==6.31.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydantic-settings==2.9.1
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.4
      - requests-toolbelt==1.0.0
      - rich==14.0.0
      - rpds-py==0.26.0
      - rsa==4.9.1
      - scipy==1.16.1
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.41
      - sse-starlette==2.4.1
      - starlette==0.47.1
      - tenacity==9.1.2
      - tiktoken==0.9.0
      - tqdm==4.67.1
      - typer==0.16.0
      - typing-extensions==4.14.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.4.0
      - uvicorn==0.35.0
      - xxhash==3.5.0
      - yarl==1.20.1
      - zstandard==0.23.0
